### ISSUE TITLE
Error on import for mint on Mac

### ISSUE THREAD

**Issue by rhewitt22** [ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions#14]
I tried importing my Mint transaction data using terminal on Mac and received the following error. Is the app coded to expect Windows file paths? I have a `transactions.csv` file in the `Imports` directory.

```
rhewitt:Monarch-Backfill-Balance-History-From-Transactions rhewitt$ python3 main.py
Would you like to import from:
1.Monarch
2.Mint
e.Exit
:2
Would you like to:
1.Convert Mint trend account balances to Monarch balances
e.Exit
:1
Traceback (most recent call last):
  File "/Users/rhewitt/web/Monarch-Backfill-Balance-History-From-Transactions/main.py", line 210, in <module>
    menu()
  File "/Users/rhewitt/web/Monarch-Backfill-Balance-History-From-Transactions/main.py", line 194, in menu
    balances = importMintBalances()
  File "/Users/rhewitt/web/Monarch-Backfill-Balance-History-From-Transactions/main.py", line 93, in importMintBalances
    selection = selectImportFile(importDir)
  File "/Users/rhewitt/web/Monarch-Backfill-Balance-History-From-Transactions/main.py", line 41, in selectImportFile
    filenames = os.listdir(importDir)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rhewitt/web/Monarch-Backfill-Balance-History-From-Transactions\\import\\'
```

**Comment by ChrisQGeorge** [comment]
Ok, I added a patch, let me know if it works, I don't have access to a mac so I can't test it

**Comment by rhewitt22** [comment]
Thanks! I pulled the latest version, the fix worked for the file path, but a new error cropped up:

```
rhewitt:Monarch-Backfill-Balance-History-From-Transactions rhewitt$ python3 main.py
Would you like to import from:
1.Monarch
2.Mint
e.Exit
:2
Would you like to:
1.Convert Mint trend account balances to Monarch balances
e.Exit
:1
Which file would you like to import? :

1: .DS_Store
2: Test_Monarch_Transactions.csv
3: Test_Mint_Trends_Debts.csv
4: transactions.csv
5: Test_Mint_Trends_Assets.csv
: 4
What is the Monarch account name?Hewitt Household
Traceback (most recent call last):
  File "/Users/rhewitt/web/Monarch-Backfill-Balance-History-From-Transactions/main.py", line 210, in <module>
    menu()
  File "/Users/rhewitt/web/Monarch-Backfill-Balance-History-From-Transactions/main.py", line 194, in menu
    balances = importMintBalances()
  File "/Users/rhewitt/web/Monarch-Backfill-Balance-History-From-Transactions/main.py", line 107, in importMintBalances
    table = sorted(unsortedTable, key = lambda row: datetime.strptime(row[0], "%b-%y"))
  File "/Users/rhewitt/web/Monarch-Backfill-Balance-History-From-Transactions/main.py", line 107, in <lambda>
    table = sorted(unsortedTable, key = lambda row: datetime.strptime(row[0], "%b-%y"))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '11/13/23' does not match format '%b-%y'
```

**Comment by ChrisQGeorge** [comment]
Yup, I just had another issue with this exact same problem https://github.com/ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions/issues/12#issuecomment-1808469871 . If you open the CSV in Excel, for some reason it will change the format on you and cause this error. You can either change the format back manually in Excel if you need to make changes in the file, but if you don't, just import the file without opening it in Excel, or don't save the file if you do open it in Excel first. 
For reference, dates that are in the monarch transaction file should be "YYYY-MM-DD" and balances imported from mint should be in the format "Month YYYY" such as "December 2023".

**Comment by rhewitt22** [comment]
You're right, I did open the file in Excel to consolidate two exports (there's a 10k row limit on exports from Mint). I just re-downloaded the data from Mint (without opening in Excel) and got the same error. 

A little research on the `datetime` module suggests `%b-%y` should result in a date in the following format: `Nov-23`. I went into Excel and used a custom format: mmm-yy. The preview shows the output `Nov-23`. When I load this up with the script I get an error suggesting the format is incorrect `ValueError: time data '29-Feb' does not match format '%b-%y'`. Somehow, despite my custom format, it's passing the date through with the day, then the month.

I tried `mmmm yyyy` (November 2023) as you suggested, too. Same result.

![Screen Shot 2023-11-13 at 1 47 30 PM](https://github.com/ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions/assets/3673374/b31ea821-e272-4b1b-ae99-bd8ac7f99ecb)

![Screen Shot 2023-11-13 at 1 47 11 PM](https://github.com/ChrisQGeorge/Monarch-Backfill-Balance-History-From-Transactions/assets/3673374/9020f1fc-ce1b-46a1-959d-f6ab720d10eb)

I'm not expecting a ton of support here, I know you did this in your spare time. Just sharing my experience on Mac!

**Comment by ChrisQGeorge** [comment]
Ok, so I think this may be a slightly different issue. At the moment, the script can't handle imported transactions directly from mint,  only the imported balance history from the Mint "trends" tab.

A good test of this would be to try and use the script on one of the test mint CSV files and see if it works.

If you want to convert transactions into a balance history, the current workflow is to first import the transactions into Monarch and then export those transactions for each account from Monarch and into the script. 

If you want to import your Mint data into Monarch can follow the Monarch Mint import guide here https://help.monarchmoney.com/hc/en-us/articles/4411877901972-Move-data-over-from-Mint-to-Monarch, or you can use there new browser extension, which I believe is supposed to be more reliable https://www.reddit.com/r/MonarchMoney/comments/17uckhp/exporting_your_data_from_mint_a_chrome_extension/.

If you want to skip importing the transactions and then exporting from Monarch, you can follow the instructions to import the month-by-month account balances from the Mint trends tab.
